### ISSUE TITLE
Async PathingRuleSet not working with Folia

### ISSUE THREAD

**Issue by shlovto** [patheloper/pathetic#46]
### Stack trace

[09:09:38] [Pathfinder Task-0/ERROR]: [Core] ===============================
[09:09:38] [Pathfinder Task-0/ERROR]: [Core] A fatal error has occurred: Failed to find path async
[09:09:38] [Pathfinder Task-0/ERROR]: [Core] Please open an issue on the Pathetic GitHub page with all this information:
[09:09:38] [Pathfinder Task-0/ERROR]: [Core] Version: 1.0.0
[09:09:38] [Pathfinder Task-0/ERROR]: [Core] Server Version: git-Folia-"3843340" (MC: 1.20.2)
[09:09:38] [Pathfinder Task-0/ERROR]: [Core] Java Version: 21.0.1
[09:09:38] [Pathfinder Task-0/ERROR]: [Core] OS: Linux
[09:09:38] [Pathfinder Task-0/ERROR]: [Core] OS Architecture: amd64
[09:09:38] [Pathfinder Task-0/ERROR]: [Core] ===============================
[09:09:38] [Pathfinder Task-0/ERROR]: [Core] java.util.concurrent.CompletionException: java.lang.IllegalStateException: Failed to find path async
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalStateException: Failed to find path async
	at GameServer-Core-1.0-SNAPSHOT-jar-with-dependencies.jar//org.patheloper.util.ErrorLogger.logFatalError(ErrorLogger.java:24)
	at GameServer-Core-1.0-SNAPSHOT-jar-with-dependencies.jar//org.patheloper.model.pathing.pathfinder.AbstractPathfinder.lambda$produceAsyncPathing$0(AbstractPathfinder.java:152)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 3 more
Caused by: java.lang.UnsupportedOperationException
	at net.minecraft.server.level.ChunkProviderServer$b.execute(ChunkProviderServer.java:865)
	at java.base/java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782)
	at java.base/java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005)
	at net.minecraft.server.level.ChunkProviderServer.a(ChunkProviderServer.java:218)
	at GameServer-Core-1.0-SNAPSHOT-jar-with-dependencies.jar//org.patheloper.nms.OneTwentyTwoNMSInterface.getSnapshot(OneTwentyTwoNMSInterface.java:36)
	at GameServer-Core-1.0-SNAPSHOT-jar-with-dependencies.jar//org.patheloper.model.snapshot.FailingSnapshotManager.getChunkSnapshot(FailingSnapshotManager.java:94)
	at GameServer-Core-1.0-SNAPSHOT-jar-with-dependencies.jar//org.patheloper.model.snapshot.FailingSnapshotManager.fetchBlock(FailingSnapshotManager.java:61)
	at GameServer-Core-1.0-SNAPSHOT-jar-with-dependencies.jar//org.patheloper.model.snapshot.FailingSnapshotManager.getBlock(FailingSnapshotManager.java:107)
	at GameServer-Core-1.0-SNAPSHOT-jar-with-dependencies.jar//org.patheloper.api.pathing.strategy.strategies.WalkablePathfinderStrategy.isValid(WalkablePathfinderStrategy.java:28)
	at GameServer-Core-1.0-SNAPSHOT-jar-with-dependencies.jar//org.patheloper.model.pathing.pathfinder.AStarPathfinder.isNodeInvalid(AStarPathfinder.java:332)
	at GameServer-Core-1.0-SNAPSHOT-jar-with-dependencies.jar//org.patheloper.model.pathing.pathfinder.AStarPathfinder.isNodeValid(AStarPathfinder.java:182)
	at GameServer-Core-1.0-SNAPSHOT-jar-with-dependencies.jar//org.patheloper.model.pathing.pathfinder.AStarPathfinder.fetchValidNeighbours(AStarPathfinder.java:283)
	at GameServer-Core-1.0-SNAPSHOT-jar-with-dependencies.jar//org.patheloper.model.pathing.pathfinder.AStarPathfinder.evaluateNewNodes(AStarPathfinder.java:158)
	at GameServer-Core-1.0-SNAPSHOT-jar-with-dependencies.jar//org.patheloper.model.pathing.pathfinder.AStarPathfinder.resolvePath(AStarPathfinder.java:62)
	at GameServer-Core-1.0-SNAPSHOT-jar-with-dependencies.jar//org.patheloper.model.pathing.pathfinder.AbstractPathfinder.lambda$produceAsyncPathing$0(AbstractPathfinder.java:150)
	... 4 more

### Actions to reproduce (if known)

Compile [Folia](https://github.com/PaperMC/Folia/tree/dev/1.20.2), use an async PathingRuleSet and try to get an path

**Comment by olijeffers0n** [comment]
We do not currently support Folia. Thank you for showing interest in using Pathetic though
